### ISSUE TITLE
[PE-D] Adding whitespaces in front of each command is invalid 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-3/tp#100]
Adding in whitespace in front of the any command is not considered as part of valid input. However, adding whitespace after `help` is considered valid. 

![image.png](https://raw.githubusercontent.com/crabnuggets/ped/main/files/63b4604a-3827-4287-a9d7-ce4a22ed7293.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: crabnuggets/ped#1

**Comment by SeanRobertDH** [comment]
Out of scope
