### ISSUE TITLE
[PE-D] `todo` allows for tasks with date/times that have already passed to be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-3/tp#107]
Given a date/time value that has already passed, the program does not reject the user's attempt at inserting such a `todo` item.

![image.png](https://raw.githubusercontent.com/crabnuggets/ped/main/files/1f3c8dd5-eeb8-4910-9060-ff40a39eb82c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: crabnuggets/ped#4

**Comment by SeanRobertDH** [comment]
Not an error. User may want to track todos that have already passed.
