### ISSUE TITLE
[PE-D] Empty description bug for deadline

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-3/tp#126]
The user guide states that the task description is a compulsory field:

![image.png](https://raw.githubusercontent.com/jonathanmui4/ped/main/files/e2745c13-cb92-4957-8e87-5b6666fce68f.png)

![image.png](https://raw.githubusercontent.com/jonathanmui4/ped/main/files/6f36c3c8-a478-4a21-8544-e445b3d47058.png)

However, when I omitted the description and put a flag, the description-less task gets created anyway.

![image.png](https://raw.githubusercontent.com/jonathanmui4/ped/main/files/0de46f8c-0988-499b-bedd-e981197293cb.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jonathanmui4/ped#8

**Comment by SeanRobertDH** [comment]
duplicate #109
